### ISSUE TITLE
'internal error' when applying 'view'

### ISSUE THREAD

**Issue by superschnuggl** [torutk/redmine_glossary#12]
Redmine version 3.3.1.stable

When I try to apply any view on the right hand side, I get an 'internal error'.

[...]/redmine/log/production.log says:
> Started PATCH "/glossary_styles/edit?glossary_style_id=1&project_id=allgemein" for xxxIPxxx at 2017-10-16 17:05:04 +0200
> Processing by GlossaryStylesController#edit as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"xxxTOKENxxx==", "glossary_style"=>{"show_desc"=>"0", "project_scope"=>"0", "groupby"=>"1", "sort_item_0"=>"id",
 "sort_item_1"=>""}, "commit"=>"Ansicht", "glossary_style_id"=>"1", "project_id"=>"allgemein"}
  Current user: xxx(id=8)
Completed 500 Internal Server Error in 20ms (ActiveRecord: 11.7ms)
> 
> ActiveRecord::StatementInvalid (PG::DatatypeMismatch: FEHLER:  Argument von WHERE muss Typ boolean haben, nicht Typ integer
LINE 1: ..."glossary_styles".* FROM "glossary_styles" WHERE (1) LIMIT 1
>                                                              ^
> : SELECT  "glossary_styles".* FROM "glossary_styles" WHERE (1) LIMIT 1):
  plugins/redmine_glossary/app/controllers/glossary_styles_controller.rb:35:in `edit'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Obviously the problem comes down to the SQL-query 'SELECT ... FROM ... WHERE (1) ...':
'(1)' is no condition.

I figured out a solution but I am not sure if it is the correct way to solve the problem:

Within file [...]/redmine/plugins/redmine_glossary/app/controllers/glossary_styles_controller.rb at line 34 I changed 
> @glossary_style = GlossaryStyle.find_by(params[:glossary_style_id])

to:

> @glossary_style = GlossaryStyle.find_by(:user_id => User.current.id)

assuming that the style setting is a per user entry.

So far it seems to work...

Is it the right way to do this? If so, it may help others to resolve this problem.

BTW: Thanks for porting this nice plugin to recent redmine versions!!!

**Comment by torutk** [comment]
Thank you for your report and fix.

I am uncertain of your fix because I only saw and modified the code needs to port for recent redmine version, that is mainly routing.

I'm glad to have your issue report, thanks!  It may help others!
